name: app_neaker
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.1
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  carousel_slider: ^5.0.0
  mongo_dart: ^0.10.4
  path_provider: ^2.1.5
  path: ^1.9.0
  assets: ^0.0.1
  convert: ^3.1.2
  flutter_rating_bar: ^4.0.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  
  assets:
      - assets/img_logo/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
